### ISSUE TITLE
Update "Helpful hints" section

### ISSUE THREAD

**Issue by AGFeldman** [caltechcs2/concurrency#2]
We should update the following section of the assignment, since we use std::thread now.

And, I'm not sure if the "You cannot call a member function from a thread directly" comment is still true. If it isn't, perhaps we should remove this hint entirely.

---

**Helpful hints**

You cannot call a member function from a thread directly; if this is something you would like to do, you will need to wrap it in a non-class function first, like this:

```
class Foo
{
    Foo() { }
    ~Foo() { }

    void f() { /* Do something interesting here. */ }
};

void *f_wrapper(void *arg)
{
    Foo *fptr = (Foo *) arg;
    fptr->f();
}

Foo *f = new Foo();
Thread *t = new Thread();
t->run(f_wrapper, (void *) f);
```

**Comment by AGFeldman** [comment]
Hi @jeffreyan11 , will you have time to do this? Thanks!

**Comment by jeffreyan11** [comment]
Hey Aaron, I'm looking into it now.
